# -*- coding: utf-8 -*-
"""LAB5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WYrH803oiyEQSUkL7toGox6-2cD5GKh
"""

import numpy as np
import pandas as pd

dataset = pd.read_csv('breast_cancer.csv')
data = pd.DataFrame(dataset)


"""Handling NaN values, By replacing them with 0"""

datanew = data.fillna(0)

b = datanew['diagnosis']
ba_Value = []
for i in range(len(b)):
    if b[i] == 'M':
        ba_Value.append(0)
    else:
        ba_Value.append(1)



datanew['diagnosis'] = ba_Value
datanew = datanew.drop(['Unnamed: 32'], axis = 1)
datanew
datanew.to_csv('new.csv',index=False)
